title: GlamRock
tagline: Rockstar, but with the glam turned up to 11.
theme: just-the-docs

url: https://glamrock.dev

defaults:
  - scope:
      path: ""
    values:
      title: GlamRock
      tagline: Rockstar, but with the glam turned up to 11.
      image: /images/rockstar-og-image.jpg
      description: "Rockstar is an esoteric programming language based on the ‘lyrical conventions of 1980s hard rock songs and power ballads.’. It was created by Dylan Beattie in 2018."

color_scheme: darkstar

include:
 - _framework

